### ISSUE TITLE
HA 2024.7 - WallPanel doesn't start

### ISSUE THREAD

**Issue by formatBCE** [j-a-n/lovelace-wallpanel#246]
As per title. After updating to Home Assistant 2024.7 Wall Panel stopped appearing. Tested in Chrome and 2 different Android browsers (including Fully Kiosk).

**Comment by mukul-k** [comment]
Same!

**Comment by danielxb-ar** [comment]
Same here

**Comment by BobMac57** [comment]
Same here

**Comment by BobMac57** [comment]
Same here

**Comment by alfredolvera** [comment]
Same here

**Comment by Tomoyochan** [comment]
The error's I am seeing are:
Uncaught TypeError: Cannot read properties of undefined (reading 'editMode')
    at WallpanelView.value (hui-view.ts:79:37)
    at wallpanel.js?hacstag=3095064164252:1146:53
    at Array.forEach (<anonymous>)
    at WallpanelView.createInfoBoxContent (wallpanel.js?hacstag=3095064164252:1132:17)
    at WallpanelView.startScreensaver (wallpanel.js?hacstag=3095064164252:2090:8)
    at WallpanelView.timer (wallpanel.js?hacstag=3095064164252:769:10)
value @ hui-view.ts:79
(anonymous) @ wallpanel.js?hacstag=3095064164252:1146
createInfoBoxContent @ wallpanel.js?hacstag=3095064164252:1132
startScreensaver @ wallpanel.js?hacstag=3095064164252:2090
timer @ wallpanel.js?hacstag=3095064164252:769
setInterval (async)
WallpanelView @ wallpanel.js?hacstag=3095064164252:675
k @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
startup @ wallpanel.js?hacstag=3095064164252:2454
setTimeout (async)
(anonymous) @ wallpanel.js?hacstag=3095064164252:2487Understand this error
wallpanel.js?hacstag=3095064164252:304 TypeError: Permissions check failed
    at enterFullscreen (wallpanel.js?hacstag=3095064164252:621:6)
    at WallpanelView.setupScreensaver (wallpanel.js?hacstag=3095064164252:2054:4)
    at WallpanelView.startScreensaver (wallpanel.js?hacstag=3095064164252:2070:8)
    at WallpanelView.timer (wallpanel.js?hacstag=3095064164252:769:10)****

**Comment by Earthweb-EWS** [comment]
Same problem here after updating HA Core to version 7.0.
Clearing cache even through devtools in browser doesn't fix the problem.

Console logs is what referenced here, appeared when Screensaver kicked in.

https://github.com/j-a-n/lovelace-wallpanel/issues/246#issuecomment-2207868313

**Comment by clintferns2911** [comment]
Yes unfortunately I raised the same issue earlier, i think I had this issue earlier than others because I was on HA Beta. Hope it get's fixed asap.

**Comment by j-a-n** [comment]
Thanks for reporting, should be fixed with v4.25.3.

**Comment by Tomoyochan** [comment]
I can confirm it is working on my system on v4.25.3.

**Comment by danielxb-ar** [comment]
It's working, thanks for the quick response !

**Comment by wgumaa** [comment]
I have updated to the latest version, but its still not working for me. Where can I find the logs?
